-- File generated by the BNF Converter (bnfc 2.9.4.1).

-- | The abstract syntax of language stately.

module AbsStately where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)

data Expr = E Action Expr | EAction Action | EVal Val
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Val = VString String | VNumber Integer | VBoolean Boolean
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Boolean = BTrue | BFalse
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Action = AWait Val | AFail | ASucc | ATask Val Val
  deriving (C.Eq, C.Ord, C.Show, C.Read)

