-- File generated by the BNF Converter (bnfc 2.9.4.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelStately where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsStately

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transExpr :: AbsStately.Expr -> Result
transExpr x = case x of
  AbsStately.E action expr -> failure x
  AbsStately.EAction action -> failure x
  AbsStately.EVal val -> failure x

transVal :: AbsStately.Val -> Result
transVal x = case x of
  AbsStately.VString string -> failure x
  AbsStately.VNumber integer -> failure x
  AbsStately.VBoolean boolean -> failure x

transBoolean :: AbsStately.Boolean -> Result
transBoolean x = case x of
  AbsStately.BTrue -> failure x
  AbsStately.BFalse -> failure x

transAction :: AbsStately.Action -> Result
transAction x = case x of
  AbsStately.AWait val -> failure x
  AbsStately.AFail -> failure x
  AbsStately.ASucc -> failure x
  AbsStately.ATask val1 val2 -> failure x
